# Generated by Django 4.2.4 on 2023-08-10 06:51

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0002_alter_cesiumprovider_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesiumviewer',
            name='terrainProviderViewModels',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='Позволяет установить провайдеры рельефа', limit_choices_to={'type': 'TerrainProvider'}, related_name='ProviderViewModel', related_query_name='ProviderViewModel', to='cesium.providerviewmodel', verbose_name='Провайдеры рельефа'),
        ),
        migrations.AlterField(
            model_name='providerviewmodel',
            name='iconUrl',
            field=models.CharField(blank=True, help_text='URL/путь до иконки тайлового сервера в блоке "Источники данных"', max_length=200, null=True, verbose_name='Иконка'),
        ),
    ]
