# Generated by Django 4.2.4 on 2023-08-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0006_cesiumbillboard_delete_cesiumbilboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolygonMaterialStyle',
            new_name='CesiumPolygonMaterialStyle',
        ),
    ]
