# Generated by Django 4.2.4 on 2023-08-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0007_rename_polygonmaterialstyle_cesiumpolygonmaterialstyle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CesiumPolygonMaterialStyle',
            new_name='CesiumPolygonMaterial',
        ),
    ]
