# Generated by Django 4.2.4 on 2023-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0008_rename_cesiumpolygonmaterialstyle_cesiumpolygonmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesiumbillboard',
            name='image',
            field=models.FileField(blank=True, default=None, help_text='Иконка для визуализации типа объекта', null=True, upload_to='bilboard_images', verbose_name='Иконка типа'),
        ),
    ]
