# Generated by Django 4.2.4 on 2023-08-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0009_alter_cesiumbillboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesiumpolyline',
            name='depthFailMaterial',
            field=models.ForeignKey(blank=True, help_text='Материал, использующийся для линии, когда она проходит под рельефом', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PolylineDepthFailMaterial', related_query_name='PolylineDepthFailMaterial', to='cesium.cesiumpolylinematerial', verbose_name='Материал под рельефом'),
        ),
        migrations.AlterField(
            model_name='cesiumpolyline',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Стандартный материал линии', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PolylineMaterial', related_query_name='PolylineMaterial', to='cesium.cesiumpolylinematerial', verbose_name='Материал'),
        ),
    ]
