# Generated by Django 4.2.4 on 2023-08-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0011_alter_cesiumbillboard_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesiumpolygon',
            name='extrudedHeight',
            field=models.FloatField(blank=True, default=0.0, help_text='Высота полигона в 3-х мерном пространстве (в метрах)', null=True, verbose_name='Высота полигона'),
        ),
        migrations.AlterField(
            model_name='cesiumpolygon',
            name='height',
            field=models.FloatField(blank=True, default=0.0, help_text='Высота полигона (в метрах) относительно поверхности Земли', null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='cesiumpolygon',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Определяет материал, используемый для отображения заливки полигона', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PolygonMaterial', related_query_name='PolygonMaterial', to='cesium.cesiumpolygonmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='cesiumpolygon',
            name='stRotation',
            field=models.FloatField(blank=True, default=0.0, help_text='Определяет поворот текстуры полигона против часовой стрелки с севера', null=True, verbose_name='Поворот'),
        ),
        migrations.AlterField(
            model_name='cesiumpolygon',
            name='zIndex',
            field=models.IntegerField(blank=True, default=0, help_text='Определяет индекс, используемый для упорядочивания полигонов при отображении. Применяется только тогда, когда параметры Height и ExtrudedHeight установлены не установлены', null=True, verbose_name='Z-индекс'),
        ),
    ]
