# Generated by Django 4.2.4 on 2023-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0012_alter_cesiumpolygon_extrudedheight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesiumbillboard',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Устанавливает объект по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumlabel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Устанавливает объект по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumpoint',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Устанавливает объект по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumpolygon',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Устанавливает объект по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumpolygonmaterial',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Использовать по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumpolyline',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Устанавливает объект по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='cesiumpolylinematerial',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Использовать по умолчанию', verbose_name='По умолчанию'),
        ),
    ]
