# Generated by Django 4.2.4 on 2023-08-14 06:25

import cesium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesium', '0013_cesiumbillboard_is_default_cesiumlabel_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesiumbillboard',
            name='image',
            field=models.FileField(blank=True, default=None, help_text='Иконка для визуализации типа объекта', null=True, upload_to='bilboard_images', validators=[cesium.models.image_file_extension_validator], verbose_name='Иконка типа'),
        ),
    ]
