# Generated by Django 4.2.4 on 2023-08-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmrgeometry',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Зона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zmr_geometry', related_query_name='zmr_geometry', to='geo_repository.zmr', verbose_name='Зона'),
        ),
    ]
