# Generated by Django 4.2.4 on 2023-08-15 06:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0002_alter_zmrgeometry_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, help_text='Показывать эту зону на карте', verbose_name='Показывать на карте')),
                ('name', models.CharField(help_text='Название охранной зоны', max_length=254, verbose_name='Имя')),
                ('description', models.TextField(blank=True, help_text='Описание ОЗ', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ОЗ',
                'verbose_name_plural': 'ОЗ',
            },
        ),
        migrations.AddField(
            model_name='zmr',
            name='is_show',
            field=models.BooleanField(default=True, help_text='Показывать эту зону на карте', verbose_name='Показывать на карте'),
        ),
        migrations.CreateModel(
            name='OZGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=True, help_text='Актуальность геометрии зоны', verbose_name='Актуальна')),
                ('date_start', models.DateTimeField(auto_now_add=True, help_text='Дата начала действия геометрии', null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, help_text='Дата окончания действия геометрии', null=True, verbose_name='Дата окончания')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Геометрия зоны', null=True, srid=4326, verbose_name='Геометрия')),
                ('zone', models.ForeignKey(blank=True, help_text='Геометрия охранной зоны объекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oz_geometry', related_query_name='oz_geometry', to='geo_repository.oz', verbose_name='Геометрия охранной зоны')),
            ],
            options={
                'verbose_name': 'Геометрия ОЗ',
                'verbose_name_plural': 'Геометрии ОЗ',
            },
        ),
    ]
