# Generated by Django 4.2.4 on 2023-08-19 16:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0003_oz_zmr_is_show_ozgeometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, help_text='Показывать этот трубопровод на карте', verbose_name='Показывать на карте')),
                ('name', models.CharField(help_text='Название трубопровода', max_length=254, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание трубопровода', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Трубопровод',
                'verbose_name_plural': 'Трубопроводы',
            },
        ),
        migrations.RenameField(
            model_name='ozgeometry',
            old_name='zone',
            new_name='parent_object',
        ),
        migrations.RenameField(
            model_name='zmrgeometry',
            old_name='zone',
            new_name='parent_object',
        ),
        migrations.CreateModel(
            name='TubeGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=True, help_text='Актуальность геометрии зоны', verbose_name='Актуальна')),
                ('date_start', models.DateTimeField(auto_now_add=True, help_text='Дата начала действия геометрии', null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, help_text='Дата окончания действия геометрии', null=True, verbose_name='Дата окончания')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='Геометрия трубопровода', null=True, srid=4326, verbose_name='Геометрия')),
                ('parent_object', models.ForeignKey(blank=True, help_text='Зона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tube_geometry', related_query_name='tube_geometry', to='geo_repository.tube', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Геометрия трубопровода',
                'verbose_name_plural': 'Геометрии трубопроводов',
            },
        ),
    ]
