# Generated by Django 4.2.4 on 2023-08-19 17:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0004_tube_rename_zone_ozgeometry_parent_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, help_text='Показывать этот объект на карте', verbose_name='Показывать на карте')),
                ('name', models.CharField(help_text='Название охраняемого объекта', max_length=254, verbose_name='Имя')),
                ('description', models.TextField(blank=True, help_text='Описание охраняемого объекта', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Охраняемый объект',
                'verbose_name_plural': 'Охраняемые объекты',
            },
        ),
        migrations.CreateModel(
            name='ProtectedObjectGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=True, help_text='Актуальность геометрии зоны', verbose_name='Актуальна')),
                ('date_start', models.DateTimeField(auto_now_add=True, help_text='Дата начала действия геометрии', null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, help_text='Дата окончания действия геометрии', null=True, verbose_name='Дата окончания')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Геометрия охраняемого объекта', null=True, srid=4326, verbose_name='Геометрия')),
                ('parent_object', models.ForeignKey(blank=True, help_text='Геометрия охраняемого объекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_object_geometry', related_query_name='protected_object_geometry', to='geo_repository.protectedobject', verbose_name='Геометрия охраняемого объекта')),
            ],
            options={
                'verbose_name': 'Геометрия охраняемого объекта',
                'verbose_name_plural': 'Геометрии охраняемых объектов',
            },
        ),
        migrations.RemoveField(
            model_name='tubegeometry',
            name='parent_object',
        ),
        migrations.DeleteModel(
            name='Tube',
        ),
        migrations.DeleteModel(
            name='TubeGeometry',
        ),
        migrations.AddField(
            model_name='oz',
            name='protected_object',
            field=models.ForeignKey(blank=True, help_text='Охраняемый объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_oz', related_query_name='protection_oz', to='geo_repository.protectedobject', verbose_name='Охраняемый объект'),
        ),
        migrations.AddField(
            model_name='zmr',
            name='protected_object',
            field=models.ForeignKey(blank=True, help_text='Охраняемый объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_zmr', related_query_name='protection_zmr', to='geo_repository.protectedobject', verbose_name='Охраняемый объект'),
        ),
    ]
