# Generated by Django 4.2.4 on 2023-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0007_alter_ozgeometry_parent_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', help_text='Имя файла', max_length=255, null=True, verbose_name='Имя')),
                ('path', models.CharField(db_column='path', help_text='Полный путь до файла или директории', max_length=255, verbose_name='Полный путь')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Дата создания', verbose_name='Дата создания')),
                ('size', models.BigIntegerField(blank=True, db_column='size', help_text='Размер в байтах', null=True, verbose_name='Размер')),
                ('minimum_level', models.IntegerField(blank=True, default=0, help_text='Минимальный масштаб', null=True, verbose_name='Минимальный масштаб')),
                ('maximum_level', models.IntegerField(blank=True, default=25, help_text='Максимальный масштаб', null=True, verbose_name='Максимальный масштаб')),
                ('min_long', models.FloatField(blank=True, default=-180, help_text='Западная граница', null=True, verbose_name='Западная граница')),
                ('min_lat', models.FloatField(blank=True, default=-90, help_text='Южная граница', null=True, verbose_name='Южная граница')),
                ('max_long', models.FloatField(blank=True, default=180, help_text='Восточная граница', null=True, verbose_name='Восточная граница')),
                ('max_lat', models.FloatField(blank=True, default=90, help_text='Северная граница', null=True, verbose_name='Северная граница')),
                ('data_type', models.CharField(blank=True, choices=[('ortho', 'Ортофотоплан'), ('dem', 'Цифровая модель рельефа')], db_column='data_type', default='ortho', help_text='Тип данных', max_length=255, null=True, verbose_name='Тип данных')),
            ],
            options={
                'verbose_name': 'Файл с геоданными',
                'verbose_name_plural': 'Файлы с геоданными',
                'db_table': 'geo_data_files',
                'ordering': ['-created'],
            },
        ),
    ]
