# Generated by Django 4.2.4 on 2023-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0008_geodatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatafile',
            name='rectangle',
            field=models.JSONField(blank=True, db_column='rectangle', help_text='Охват тайлового слоя', null=True, verbose_name='Охват'),
        ),
    ]
