# Generated by Django 4.2.4 on 2023-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0009_geodatafile_rectangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodatafile',
            name='max_lat',
        ),
        migrations.RemoveField(
            model_name='geodatafile',
            name='max_long',
        ),
        migrations.RemoveField(
            model_name='geodatafile',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='geodatafile',
            name='min_long',
        ),
        migrations.RemoveField(
            model_name='geodatafile',
            name='rectangle',
        ),
        migrations.AddField(
            model_name='geodatafile',
            name='tileHeight',
            field=models.IntegerField(blank=True, default=256, help_text='Высота тайла', null=True, verbose_name='Высота тайла'),
        ),
        migrations.AddField(
            model_name='geodatafile',
            name='tileWidth',
            field=models.IntegerField(blank=True, default=256, help_text='Ширина тайла', null=True, verbose_name='Ширина тайла'),
        ),
    ]
