# Generated by Django 4.2.4 on 2023-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0010_remove_geodatafile_max_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatafile',
            name='is_show',
            field=models.BooleanField(default=True, help_text='Показывать этот слой на карте', verbose_name='Показывать на карте'),
        ),
    ]
