# Generated by Django 4.2.4 on 2023-08-30 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_repository', '0011_geodatafile_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatafile',
            name='rectangle',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Охват тайлового слоя', null=True, srid=4326, verbose_name='Охват'),
        ),
    ]
